FROM python:3.11

WORKDIR /code

# RUN git clone https://github.com/adbouk-1/4-week-project.git

COPY . ./code/

RUN apt-get -y -q update && \
  apt-get -y install \
  cmake g++ git python3 python3-pip python3-dev python3-venv \
  psmisc libfmt-dev libdrm-dev gcc make \
  libyaml-dev python3-yaml python3-ply python3-jinja2 \
  libssl-dev openssl libcamera-dev meson libcap-dev

# RUN apt-get -y install python3-picamera2
    
RUN cd ./code/ 
RUN python -m venv .
ENV PATH="/opt/venv/bin:$PATH"

RUN apt-get remove libcamera0
RUN pip3 install jinja2 ply PyYAML

RUN git clone https://github.com/raspberrypi/libcamera.git && \
    cd libcamera && \
    meson setup build && \
    ninja -C build install

RUN pip3 install -r ./code/requirements.txt

# RUN python ./code/main.py

# RUN python main.py

CMD ["python ./code/main.py"]



