FROM python:3.11

WORKDIR /code​

RUN git clone https://github.com/adbouk-1/4-week-project.git 4-week-project

COPY 4-week-project/src ./code/​

RUN apt-get update​ &&\
    cd ./code/ &&\
    python -m venv . &&\
    source /bin/activate &&\
    pip3 install -r ./code/requirements.txt​

RUN python main.py

CMD ["sleep infinity"]



